composer.json
composer.lock

D9 - Update CD to 7.4

---

composer.json
composer.lock
patches/common_design-drupal-10-compatibility.patch

D10 - Update CD to 7.4

---

composer.lock
composer.patches.json
patches/user_expire-customize-notification-email.patch
patches/user_expire-reset-expiration-on-reactivation.patch

Refs: OPS-9045
Not sure what happened with https://github.com/UN-OCHA/drupal-starterkit/actions/runs/4012864115/jobs/6903879416:
```
Fetching the repository
/usr/bin/git -c protocol.version=2 fetch --no-tags --prune --progress --no-recurse-submodules --depth=1 origin +refs/heads/develop*:refs/remotes/origin/develop* +refs/tags/develop*:refs/tags/develop*
The process '/usr/bin/git' failed with exit code 1
```
Also moves patches for user_expire as per OPS-8689.

chore: update packages manually as periodic update failed

---

composer.lock
composer.patches.json

chore: update manually as automatic run failed

---

.docksal/docksal.env
.docksal/etc/php/php.ini
.github/workflows/run-tests.yml
composer.json
composer.lock
docker/Dockerfile
html/modules/custom/starter_module/starter_module.info.yml
html/modules/custom/starter_module/starter_module.module
html/modules/custom/starter_module/tests/src/ExistingSite/HomePageTest.php
phpunit.xml
tests/docker-compose.yml

chore: Use github actions for tests

---

local/docker-compose.yml
tests/docker-compose.yml

Also use our images for the local stack and fix the entrypoint for the memache container.

fix: use our memcache and mysql images

---

.github/workflows/run-tests.yml

1. Test code from custom themes as well
2. Fix output formatting
3. Skip coverage step when there are no tests

Test action fixes

---

.github/workflows/run-tests.yml

Refs: local tests
Bringing in line with the other repos.

chore: update tests for local

---

.github/workflows/run-tests.yml

chore: fix pasted error

---

config/social_auth.settings.yml

chore: change post-login redirect url

---

composer.patches.json

chore: remove patch which has been merged

---

.gitignore
local/.env.example
local/README.md
local/docker-compose.yml
local/exec.sh
local/install.sh

chore: align local set up with standard

---

local/docker-compose.yml

chore: fix variable

---

local/docker-compose.yml

bump local mysql version

---

config/user.role.administrator.yml

No more google tag

---

config/config_split.config_split.config_dev.yml
config/core.entity_form_display.user.user.default.yml
config/core.entity_form_mode.media.media_library.yml
config/core.entity_form_mode.user.register.yml
config/core.entity_view_mode.block.token.yml
config/core.entity_view_mode.file.token.yml
config/core.entity_view_mode.media.full.yml
config/core.entity_view_mode.media.media_library.yml
config/core.entity_view_mode.menu_link_content.token.yml
config/core.entity_view_mode.node.full.yml
config/core.entity_view_mode.node.rss.yml
config/core.entity_view_mode.node.search_index.yml
config/core.entity_view_mode.node.search_result.yml
config/core.entity_view_mode.node.teaser.yml
config/core.entity_view_mode.node.token.yml
config/core.entity_view_mode.paragraph.preview.yml
config/core.entity_view_mode.path_alias.token.yml
config/core.entity_view_mode.social_auth.token.yml
config/core.entity_view_mode.taxonomy_term.full.yml
config/core.entity_view_mode.user.compact.yml
config/core.entity_view_mode.user.full.yml
config/core.entity_view_mode.user.token.yml
config/editor.editor.text_editor_simple.yml
config/filter.format.plain_text.yml
config/views.view.files.yml
config/views.view.glossary.yml
config/views.view.media_library.yml
config/views.view.monitoring_sensor_results.yml
config/views.view.taxonomy_term.yml

chore: bring config up to date

---

config/seckit.settings.yml
local/docker-compose.yml

chore: allow more google tracking

---

.github/workflows/composer-update.yml
tests/docker-compose.yml

chore: test including config in updates

---

.github/workflows/composer-update.yml

chore: include missing credentials

---

.github/workflows/composer-update.yml

chore: revert change until the branch can be merged

---

composer.json
composer.lock

chore: use our version of gtm_barebones

---

PATCHES/user_expire-customize-notification-email.patch
PATCHES/user_expire-reset-expiration-on-reactivation.patch
composer.json
composer.lock

chore: update patches and stage_file_proxy module

---

config/seckit.settings.yml

chore: disallow data: for csp

---

config/seckit.settings.yml

- **chore: disallow data: for csp**
- **chore: csp add data: for img-src**

OPS 10754 csp adjustments

---

composer.lock
composer.patches.json

updates: update packages

---

.github/workflows/run-tests.yml

feat: Grep the PHP logs on error, and show any fatals in the PR comment.

---

composer.lock
composer.patches.json
config/user_expire.settings.yml

updates: update user_expire module

---

config/imagemagick.settings.yml

chore: set imagemagick version in config

---

composer.json
composer.lock
config/core.extension.yml
docker/Dockerfile

chore: remove allowed_formats module

---

PATCHES/social_auth-type-error-3496656.patch
composer.json
composer.lock
composer.patches.json

bug: social_auth patch

---

composer.json
composer.lock
composer.patches.json

updates: update social_auth_hid module

---

composer.json
composer.lock

updates: bump packages which interfere with weekly updates

---

composer.json
composer.lock

updates: try backward_compatibility module

---

composer.json
composer.lock

- **updates: try backward_compatibility module**
- **chore: remove module which didn't help**

OPS 10683 post updates

---

.github/workflows/composer-update-scripts.yml

updates: try action fork with updates flag

---

local/shared/settings/settings.memcache.php

Refs: OPS-11411
As per https://github.com/UN-OCHA/gms-site/pull/544

updates: update local memcache settings

---

.github/workflows/composer-update-scripts.yml
.github/workflows/composer-update.yml

updates: run workflow with scripts
